version: '2'
services:
    example-app:
        image: example
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://example-mysql:3306/example?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_JEST_URI=http://example-elasticsearch:9200
        ports:
            - 8080:8080
    example-mysql:
        extends:
            file: mysql.yml
            service: example-mysql
    example-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: example-elasticsearch
